version: '2'

services:
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      
  prom:
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/prometheus.yml
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
      
  influxdb:
    image: influxdb:1.7
    ports:
      - "8086:8086"

    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro


  exporter:
    image: prom/collectd-exporter
    ports:
      - "9103:9103"
      - "25826:25826/udp"
    command:
      - "-collectd.listen-address=:25826"

    
